### PR TITLE
Add sass

### PR DESCRIPTION
**Pull request by chazelex**
This is a simple Sass addition where we use the CLI node-sass methods in package.json to build out the Sass files. In some possible future iterations, this will be broken out into its own JS file. These changes include the following:
- Install node-sass into the environment (both package files).
- Set up the Sass source folder structure. I envision that the "src" folder will house all the site and build it out to "www" in the future. Reminder: Sass files with the "_" prefix are not compiled; they are included in other Sass files (i.e., bingo-card.scss).
- Tweak the server structure for css files.
- Separate the styles I see as being modified for future skins into layout and default (i.e., the default skin).
- add the "build" script which is run before starting the server or deploying to ensure the CSS has all the changes.

**To Do:** Add a dev option to watch for changes. I tried the --watch parameter with node-sass but it would not allow the server to run or it would not run at all if the server were started first. This will need some deep work to get Express to reload/restart upon file changes, and we'll need to recompile css if the Sass files change. 

**package-lock.json changes**
@HaroldPutman It looks like Google cloud bundles were removed because they were never installed from the original package.json. What do I need to do to get those back in (i.e., how did you install it)? I'll get that added back and add a dependency in the package.json file to ensure they don't change.

### CODE REVIEW

**Comment by chazelex** [comment]
@HaroldPutman Is there some reason I cannot add you as a reviewer for this PR? I cannot make any changes to the content in the right sidebar for this PR. ?

**Comment by HaroldPutman** [comment]
It's interesting how quickly and necessarily a project started in JSFiddle can grow into something big. I added myself as a reviewer, not sure why you would not be able to do that, this is a public repo. I will have a closer look at this and do a review as I get time. I'll also publish my todo list as issues here so you can see where I am heading with it.

**Comment by chazelex** [comment]
@HaroldPutman I figured we could use this as a pet project to try out new things and explore some fun stuff. ;) At some point we could then use this as a starting point to translate it into other technologies to try those out (perhaps as separate branches?) Dreams....

**Comment by HaroldPutman** [comment]
Definitely the goal is always to learn new things!

**Comment by HaroldPutman** [comment]
Regarding the Google cloud changes in package-lock.json I started down the path of writing a script to rsync the files to GCP Storage, but then I realized there was already a command line utility to do that. That's the bad part about package-lock, you have to remember to regenerate it from scratch if you un-require some modules.

Like I mention in #9 The real solution is to use CI/CD rather than push from local.

**Comment by HaroldPutman** [comment]
We don't necessarily need for this PR, but here is how to get express to recompile the sass https://stackoverflow.com/questions/23711897/get-sass-to-autocompile-with-nodejs-express-and-node-sass

**Comment by HaroldPutman** [comment]
To answer my own question about multiple CSS files, I suppose this approach would allow for alternate style sheets. Which is interesting, but I think the main use case for skinning this would not be for end user to choose skins, but for creating a themed bingo game. Like Travel Bingo to play on a long car ride, or buzzword bingo to play during corporate meetings.

**Comment by chazelex** [comment]
@HaroldPutman I am intending to add a dropdown for the user to change skins, loading the CSS on-the-fly. It should be similar to a test page I created some time ago here (the Styles dropdown in the top right):

- [Header Test Page](http://lexmark-web-design-playground.s3-website-us-east-1.amazonaws.com/examples/lexmark/themes/lxk/headers/#)

I envision the skins being something akin to Light, Dark, etc. along with anything fun we might want to add (background images, etc.).

**Comment by chazelex** [comment]
@HaroldPutman FYI: I will get back to this hopefully this weekend.

**Comment by HaroldPutman** [comment]
Ah, Good thinking "Dark  mode" is essential these days.
I want to keep the interface really minimal, but It does seem like a popup menu is inevitable. (See #6 and #11)

**Comment by chazelex** [comment]
@HaroldPutman Maybe the additional menu items need to be some sort of minimal menu item to access the rest--something akin to the hamburger menu.

**Comment by HaroldPutman** [comment]
Now that I have CI/CD working I think I will take the parts of this PR and implement in a new PR.

**Comment by chazelex** [comment]
@HaroldPutman Feel free to implement in another PR and let me know once you have.

**Comment by chazelex** [comment]
@HaroldPutman Are going to keep the "www" folder after all? I am assuming you'll be using a "src" folder as I have here for all source files to be built out (copied for now) to a "www" folder, right?

**Comment by HaroldPutman** [comment]
Replaced with #19

**Pull request closed without merging**
